// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fyralabs/id-server/ent/predicate"
	"github.com/fyralabs/id-server/ent/totpmethod"
)

// TOTPMethodDelete is the builder for deleting a TOTPMethod entity.
type TOTPMethodDelete struct {
	config
	hooks    []Hook
	mutation *TOTPMethodMutation
}

// Where appends a list predicates to the TOTPMethodDelete builder.
func (tmd *TOTPMethodDelete) Where(ps ...predicate.TOTPMethod) *TOTPMethodDelete {
	tmd.mutation.Where(ps...)
	return tmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tmd *TOTPMethodDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tmd.hooks) == 0 {
		affected, err = tmd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TOTPMethodMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tmd.mutation = mutation
			affected, err = tmd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tmd.hooks) - 1; i >= 0; i-- {
			if tmd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tmd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tmd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (tmd *TOTPMethodDelete) ExecX(ctx context.Context) int {
	n, err := tmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tmd *TOTPMethodDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: totpmethod.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: totpmethod.FieldID,
			},
		},
	}
	if ps := tmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, tmd.driver, _spec)
}

// TOTPMethodDeleteOne is the builder for deleting a single TOTPMethod entity.
type TOTPMethodDeleteOne struct {
	tmd *TOTPMethodDelete
}

// Exec executes the deletion query.
func (tmdo *TOTPMethodDeleteOne) Exec(ctx context.Context) error {
	n, err := tmdo.tmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{totpmethod.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tmdo *TOTPMethodDeleteOne) ExecX(ctx context.Context) {
	tmdo.tmd.ExecX(ctx)
}
