// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fyralabs/id-server/ent/predicate"
	"github.com/fyralabs/id-server/ent/totpmethod"
	"github.com/fyralabs/id-server/ent/user"
	"github.com/google/uuid"
)

// TOTPMethodQuery is the builder for querying TOTPMethod entities.
type TOTPMethodQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TOTPMethod
	// eager-loading edges.
	withUser *UserQuery
	withFKs  bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TOTPMethodQuery builder.
func (tmq *TOTPMethodQuery) Where(ps ...predicate.TOTPMethod) *TOTPMethodQuery {
	tmq.predicates = append(tmq.predicates, ps...)
	return tmq
}

// Limit adds a limit step to the query.
func (tmq *TOTPMethodQuery) Limit(limit int) *TOTPMethodQuery {
	tmq.limit = &limit
	return tmq
}

// Offset adds an offset step to the query.
func (tmq *TOTPMethodQuery) Offset(offset int) *TOTPMethodQuery {
	tmq.offset = &offset
	return tmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tmq *TOTPMethodQuery) Unique(unique bool) *TOTPMethodQuery {
	tmq.unique = &unique
	return tmq
}

// Order adds an order step to the query.
func (tmq *TOTPMethodQuery) Order(o ...OrderFunc) *TOTPMethodQuery {
	tmq.order = append(tmq.order, o...)
	return tmq
}

// QueryUser chains the current query on the "user" edge.
func (tmq *TOTPMethodQuery) QueryUser() *UserQuery {
	query := &UserQuery{config: tmq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(totpmethod.Table, totpmethod.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, totpmethod.UserTable, totpmethod.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(tmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TOTPMethod entity from the query.
// Returns a *NotFoundError when no TOTPMethod was found.
func (tmq *TOTPMethodQuery) First(ctx context.Context) (*TOTPMethod, error) {
	nodes, err := tmq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{totpmethod.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tmq *TOTPMethodQuery) FirstX(ctx context.Context) *TOTPMethod {
	node, err := tmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TOTPMethod ID from the query.
// Returns a *NotFoundError when no TOTPMethod ID was found.
func (tmq *TOTPMethodQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tmq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{totpmethod.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tmq *TOTPMethodQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TOTPMethod entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TOTPMethod entity is found.
// Returns a *NotFoundError when no TOTPMethod entities are found.
func (tmq *TOTPMethodQuery) Only(ctx context.Context) (*TOTPMethod, error) {
	nodes, err := tmq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{totpmethod.Label}
	default:
		return nil, &NotSingularError{totpmethod.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tmq *TOTPMethodQuery) OnlyX(ctx context.Context) *TOTPMethod {
	node, err := tmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TOTPMethod ID in the query.
// Returns a *NotSingularError when more than one TOTPMethod ID is found.
// Returns a *NotFoundError when no entities are found.
func (tmq *TOTPMethodQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tmq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{totpmethod.Label}
	default:
		err = &NotSingularError{totpmethod.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tmq *TOTPMethodQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TOTPMethods.
func (tmq *TOTPMethodQuery) All(ctx context.Context) ([]*TOTPMethod, error) {
	if err := tmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tmq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tmq *TOTPMethodQuery) AllX(ctx context.Context) []*TOTPMethod {
	nodes, err := tmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TOTPMethod IDs.
func (tmq *TOTPMethodQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := tmq.Select(totpmethod.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tmq *TOTPMethodQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tmq *TOTPMethodQuery) Count(ctx context.Context) (int, error) {
	if err := tmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tmq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tmq *TOTPMethodQuery) CountX(ctx context.Context) int {
	count, err := tmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tmq *TOTPMethodQuery) Exist(ctx context.Context) (bool, error) {
	if err := tmq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tmq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tmq *TOTPMethodQuery) ExistX(ctx context.Context) bool {
	exist, err := tmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TOTPMethodQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tmq *TOTPMethodQuery) Clone() *TOTPMethodQuery {
	if tmq == nil {
		return nil
	}
	return &TOTPMethodQuery{
		config:     tmq.config,
		limit:      tmq.limit,
		offset:     tmq.offset,
		order:      append([]OrderFunc{}, tmq.order...),
		predicates: append([]predicate.TOTPMethod{}, tmq.predicates...),
		withUser:   tmq.withUser.Clone(),
		// clone intermediate query.
		sql:    tmq.sql.Clone(),
		path:   tmq.path,
		unique: tmq.unique,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (tmq *TOTPMethodQuery) WithUser(opts ...func(*UserQuery)) *TOTPMethodQuery {
	query := &UserQuery{config: tmq.config}
	for _, opt := range opts {
		opt(query)
	}
	tmq.withUser = query
	return tmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Secret string `json:"secret,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TOTPMethod.Query().
//		GroupBy(totpmethod.FieldSecret).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tmq *TOTPMethodQuery) GroupBy(field string, fields ...string) *TOTPMethodGroupBy {
	group := &TOTPMethodGroupBy{config: tmq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tmq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Secret string `json:"secret,omitempty"`
//	}
//
//	client.TOTPMethod.Query().
//		Select(totpmethod.FieldSecret).
//		Scan(ctx, &v)
//
func (tmq *TOTPMethodQuery) Select(fields ...string) *TOTPMethodSelect {
	tmq.fields = append(tmq.fields, fields...)
	return &TOTPMethodSelect{TOTPMethodQuery: tmq}
}

func (tmq *TOTPMethodQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tmq.fields {
		if !totpmethod.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tmq.path != nil {
		prev, err := tmq.path(ctx)
		if err != nil {
			return err
		}
		tmq.sql = prev
	}
	return nil
}

func (tmq *TOTPMethodQuery) sqlAll(ctx context.Context) ([]*TOTPMethod, error) {
	var (
		nodes       = []*TOTPMethod{}
		withFKs     = tmq.withFKs
		_spec       = tmq.querySpec()
		loadedTypes = [1]bool{
			tmq.withUser != nil,
		}
	)
	if tmq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, totpmethod.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &TOTPMethod{config: tmq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, tmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := tmq.withUser; query != nil {
		ids := make([]uuid.UUID, 0, len(nodes))
		nodeids := make(map[uuid.UUID][]*TOTPMethod)
		for i := range nodes {
			if nodes[i].user_totp_methods == nil {
				continue
			}
			fk := *nodes[i].user_totp_methods
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_totp_methods" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.User = n
			}
		}
	}

	return nodes, nil
}

func (tmq *TOTPMethodQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tmq.querySpec()
	_spec.Node.Columns = tmq.fields
	if len(tmq.fields) > 0 {
		_spec.Unique = tmq.unique != nil && *tmq.unique
	}
	return sqlgraph.CountNodes(ctx, tmq.driver, _spec)
}

func (tmq *TOTPMethodQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tmq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tmq *TOTPMethodQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   totpmethod.Table,
			Columns: totpmethod.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: totpmethod.FieldID,
			},
		},
		From:   tmq.sql,
		Unique: true,
	}
	if unique := tmq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tmq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, totpmethod.FieldID)
		for i := range fields {
			if fields[i] != totpmethod.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tmq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tmq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tmq *TOTPMethodQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tmq.driver.Dialect())
	t1 := builder.Table(totpmethod.Table)
	columns := tmq.fields
	if len(columns) == 0 {
		columns = totpmethod.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tmq.sql != nil {
		selector = tmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tmq.unique != nil && *tmq.unique {
		selector.Distinct()
	}
	for _, p := range tmq.predicates {
		p(selector)
	}
	for _, p := range tmq.order {
		p(selector)
	}
	if offset := tmq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tmq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TOTPMethodGroupBy is the group-by builder for TOTPMethod entities.
type TOTPMethodGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tmgb *TOTPMethodGroupBy) Aggregate(fns ...AggregateFunc) *TOTPMethodGroupBy {
	tmgb.fns = append(tmgb.fns, fns...)
	return tmgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tmgb *TOTPMethodGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tmgb.path(ctx)
	if err != nil {
		return err
	}
	tmgb.sql = query
	return tmgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tmgb *TOTPMethodGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tmgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (tmgb *TOTPMethodGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tmgb.fields) > 1 {
		return nil, errors.New("ent: TOTPMethodGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tmgb *TOTPMethodGroupBy) StringsX(ctx context.Context) []string {
	v, err := tmgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tmgb *TOTPMethodGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tmgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{totpmethod.Label}
	default:
		err = fmt.Errorf("ent: TOTPMethodGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tmgb *TOTPMethodGroupBy) StringX(ctx context.Context) string {
	v, err := tmgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (tmgb *TOTPMethodGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tmgb.fields) > 1 {
		return nil, errors.New("ent: TOTPMethodGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tmgb *TOTPMethodGroupBy) IntsX(ctx context.Context) []int {
	v, err := tmgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tmgb *TOTPMethodGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tmgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{totpmethod.Label}
	default:
		err = fmt.Errorf("ent: TOTPMethodGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tmgb *TOTPMethodGroupBy) IntX(ctx context.Context) int {
	v, err := tmgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (tmgb *TOTPMethodGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tmgb.fields) > 1 {
		return nil, errors.New("ent: TOTPMethodGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tmgb *TOTPMethodGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tmgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tmgb *TOTPMethodGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tmgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{totpmethod.Label}
	default:
		err = fmt.Errorf("ent: TOTPMethodGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tmgb *TOTPMethodGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tmgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (tmgb *TOTPMethodGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tmgb.fields) > 1 {
		return nil, errors.New("ent: TOTPMethodGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tmgb *TOTPMethodGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tmgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tmgb *TOTPMethodGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tmgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{totpmethod.Label}
	default:
		err = fmt.Errorf("ent: TOTPMethodGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tmgb *TOTPMethodGroupBy) BoolX(ctx context.Context) bool {
	v, err := tmgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tmgb *TOTPMethodGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tmgb.fields {
		if !totpmethod.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tmgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tmgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tmgb *TOTPMethodGroupBy) sqlQuery() *sql.Selector {
	selector := tmgb.sql.Select()
	aggregation := make([]string, 0, len(tmgb.fns))
	for _, fn := range tmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tmgb.fields)+len(tmgb.fns))
		for _, f := range tmgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tmgb.fields...)...)
}

// TOTPMethodSelect is the builder for selecting fields of TOTPMethod entities.
type TOTPMethodSelect struct {
	*TOTPMethodQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tms *TOTPMethodSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tms.prepareQuery(ctx); err != nil {
		return err
	}
	tms.sql = tms.TOTPMethodQuery.sqlQuery(ctx)
	return tms.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tms *TOTPMethodSelect) ScanX(ctx context.Context, v interface{}) {
	if err := tms.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (tms *TOTPMethodSelect) Strings(ctx context.Context) ([]string, error) {
	if len(tms.fields) > 1 {
		return nil, errors.New("ent: TOTPMethodSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tms *TOTPMethodSelect) StringsX(ctx context.Context) []string {
	v, err := tms.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (tms *TOTPMethodSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tms.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{totpmethod.Label}
	default:
		err = fmt.Errorf("ent: TOTPMethodSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tms *TOTPMethodSelect) StringX(ctx context.Context) string {
	v, err := tms.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (tms *TOTPMethodSelect) Ints(ctx context.Context) ([]int, error) {
	if len(tms.fields) > 1 {
		return nil, errors.New("ent: TOTPMethodSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tms *TOTPMethodSelect) IntsX(ctx context.Context) []int {
	v, err := tms.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (tms *TOTPMethodSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tms.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{totpmethod.Label}
	default:
		err = fmt.Errorf("ent: TOTPMethodSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tms *TOTPMethodSelect) IntX(ctx context.Context) int {
	v, err := tms.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (tms *TOTPMethodSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tms.fields) > 1 {
		return nil, errors.New("ent: TOTPMethodSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tms *TOTPMethodSelect) Float64sX(ctx context.Context) []float64 {
	v, err := tms.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (tms *TOTPMethodSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tms.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{totpmethod.Label}
	default:
		err = fmt.Errorf("ent: TOTPMethodSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tms *TOTPMethodSelect) Float64X(ctx context.Context) float64 {
	v, err := tms.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (tms *TOTPMethodSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tms.fields) > 1 {
		return nil, errors.New("ent: TOTPMethodSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tms *TOTPMethodSelect) BoolsX(ctx context.Context) []bool {
	v, err := tms.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (tms *TOTPMethodSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tms.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{totpmethod.Label}
	default:
		err = fmt.Errorf("ent: TOTPMethodSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tms *TOTPMethodSelect) BoolX(ctx context.Context) bool {
	v, err := tms.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tms *TOTPMethodSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tms.sql.Query()
	if err := tms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
