// Code generated by entc, DO NOT EDIT.

package totpmethod

import (
	"time"
)

const (
	// Label holds the string label denoting the totpmethod type in the database.
	Label = "totp_method"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSecret holds the string denoting the secret field in the database.
	FieldSecret = "secret"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldLastUsedAt holds the string denoting the lastusedat field in the database.
	FieldLastUsedAt = "last_used_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the totpmethod in the database.
	Table = "totp_methods"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "totp_methods"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_totp_methods"
)

// Columns holds all SQL columns for totpmethod fields.
var Columns = []string{
	FieldID,
	FieldSecret,
	FieldCreatedAt,
	FieldLastUsedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "totp_methods"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_totp_methods",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
)
